spring:
  profiles:
    active: development
---

spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eurekao/spring-boot-microservice-config
        health:
          repositories:
            movie:
              label: master
server:
  port: 8888
